name: 🐛 Bug Report
description: Report a bug to help us improve BrightWell Website
title: "[BUG] "
labels: ["bug", "triage"]
assignees: [bug]

body:
  - type: markdown
    attributes:
      value: |
        ## 🏥 BrightWell Medical Billing - Bug Report

        Thank you for reporting a bug! This helps us improve our medical billing platform.
        Please fill out the sections below to help us understand and resolve the issue.

  - type: checkboxes
    id: preliminary-checks
    attributes:
      label: 🔍 Preliminary Checks
      description: Please confirm you have completed these checks
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have tested this on the latest version
          required: true
        - label: I have checked the documentation
          required: true

  - type: dropdown
    id: bug-category
    attributes:
      label: 🏷️ Bug Category
      description: What category does this bug fall into?
      options:
        - "🎨 UI/UX Issues"
        - "⚡ Performance Problems"
        - "🔒 Security Concerns"
        - "📱 Responsive/Mobile Issues"
        - "🔧 Functionality Bugs"
        - "♿ Accessibility Issues"
        - "🏥 Medical Billing Specific"
        - "📊 Data/Analytics Issues"
        - "🚀 Build/Deployment Problems"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 🚨 Severity Level
      description: How severe is this bug?
      options:
        - "🔴 Critical - System unusable/broken"
        - "🟠 High - Major functionality affected"
        - "🟡 Medium - Minor functionality affected"
        - "🔵 Low - Cosmetic/minor issue"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 📝 Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: What you expected to happen
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: 🌐 Browser
      description: Which browser(s) are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Opera
        - Internet Explorer
        - Mobile Safari (iOS)
        - Chrome Mobile (Android)
        - Other
    validations:
      required: true

  - type: dropdown
    id: devices
    attributes:
      label: 📱 Device Type
      description: What device are you using?
      multiple: true
      options:
        - Desktop/Laptop
        - Tablet
        - Mobile Phone
        - Other
    validations:
      required: true

  - type: input
    id: screen-resolution
    attributes:
      label: 📺 Screen Resolution
      description: What is your screen resolution?
      placeholder: "e.g., 1920x1080, 375x812"

  - type: textarea
    id: console-errors
    attributes:
      label: 🚨 Console Errors
      description: Any errors in the browser console? (Press F12 → Console tab)
      placeholder: Paste any error messages here
      render: text

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 Screenshots/Videos
      description: If applicable, add screenshots or videos to help explain your problem
      placeholder: Drag and drop images/videos here or paste links

  - type: checkboxes
    id: medical-billing-impact
    attributes:
      label: 🏥 Medical Billing Impact
      description: Does this bug affect medical billing functionality?
      options:
        - label: Affects claims processing
        - label: Impacts billing accuracy
        - label: Affects revenue cycle management
        - label: Impacts compliance/HIPAA
        - label: Not related to medical billing

  - type: textarea
    id: additional-context
    attributes:
      label: 📋 Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful

  - type: checkboxes
    id: contribution
    attributes:
      label: 🤝 Contribution
      description: Would you like to contribute to fixing this bug?
      options:
        - label: I would like to work on fixing this bug
        - label: I can provide additional testing
        - label: I can help with documentation updates
